#!/bin/sh

source $(dirname "$0")/include

NAME=bitcoin
APP_DIR=/opt/${NAME}/bin
PROC=${NAME}-qt
APP=$APP_DIR/$PROC
CONF=daemon_not_note.conf

ARGS="-conf=$CONF"
#ARGS="$ARGS -txindex=1"

main() {
    log "Starting $APP"
    runWallet
    delay 120
    ARGS="$ARGS -reindex"
    runWallet
}

main
