#!/bin/sh

source $(dirname "$0")/include

NAME=zen
APP_DIR=/opt/${NAME}/bin
PROC=${NAME}d
APP=$APP_DIR/$PROC
CONF=daemon_not_note.conf

ARGS="-conf=$CONF -datadir=$WORK_DIR/blockchains/$NAME"
#ARGS="$ARGS -txindex=1"

main() {
    log "Starting $APP"
    runWallet
    delay 120
    ARGS="$ARGS -reindex -rescan"
    #ARGS="$ARGS -reindex -rescan"
    runWallet
}

main
